name: Extract ZIP

on: [push]

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cek file
        run: ls -lah

      - name: Buat folder
        run: mkdir -p hasil/extrak

      - name: Extract zip
        run: unzip Bahan-Radmon.zip -d hasil/extrak
