name: Auto Extract ZIP to Root (No Folder)
// extract mati + [ workflow_dispatch ],nyala + [ main ]
on:
  push:
    branches: [ workflow_dispatch ]

permissions:
  contents: write

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract zip
        run: unzip -o Electro-Bootstrap-1.0.0.zip

      - name: Pindahkan isi folder ke root
        run: |
          shopt -s dotglob
          mv Electro-Bootstrap-1.0.0/* .
          rm -rf Electro-Bootstrap-1.0.0

      - name: Commit hasil extract
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Auto extract zip to clean root" || echo "Tidak ada perubahan"
          git push
